read_module ZG3.rm
read_spec ZG3_ATL_bis.spec


atl_check ZG3 Btimeliness_B
atl_check ZG3 Btimeliness_B_Reseau
atl_check ZG3 Btimeliness_B_Horloge
atl_check ZG3 Btimeliness_B_Reseau_Horloge
atl_check ZG3 Btimeliness_Reseau
atl_check ZG3 Btimeliness_Reseau_Horloge
atl_check ZG3 Btimeliness_Horloge
atl_check ZG3 A_non_repudiation
atl_check ZG3 A_non_repudiation_B
atl_check ZG3 A_non_repudiation_B_reseau
atl_check ZG3 A_non_repudiation_B_Horloge
atl_check ZG3 A_non_repudiation_B_reseau_Horloge
atl_check ZG3 A_non_repudiation_reseau
atl_check ZG3 A_non_repudiation_reseau_Horloge
atl_check ZG3 A_non_repudiation_Horloge
atl_check ZG3 B_non_repudiation
atl_check ZG3 B_non_repudiation_A
atl_check ZG3 B_non_repudiation_A_reseau
atl_check ZG3 B_non_repudiation_A_Horloge
atl_check ZG3 B_non_repudiation_A_reseau_Horloge
atl_check ZG3 B_non_repudiation_reseau
atl_check ZG3 B_non_repudiation_reseau_Horloge
atl_check ZG3 B_non_repudiation_Horloge
exit

