read_module ZG4.rm
read_spec ZG3_ATL_bis.spec

atl_check ZG4 Btimeliness
atl_check ZG4 Btimeliness_A
atl_check ZG4 Btimeliness_A_B
atl_check ZG4 Btimeliness_A_Reseau
atl_check ZG4 Btimeliness_A_Horloge
atl_check ZG4 Btimeliness_A_B_Reseau
atl_check ZG4 Btimeliness_A_B_Horloge
atl_check ZG4 Btimeliness_A_Reseau_Horloge
atl_check ZG4 Btimeliness_A_B_Reseau_Horloge
atl_check ZG4 Btimeliness_B
atl_check ZG4 Btimeliness_B_Reseau
atl_check ZG4 Btimeliness_B_Horloge
atl_check ZG4 Btimeliness_B_Reseau_Horloge
atl_check ZG4 Btimeliness_Reseau
atl_check ZG4 Btimeliness_Reseau_Horloge
atl_check ZG4 Btimeliness_Horloge
atl_check ZG4 A_non_repudiation
atl_check ZG4 A_non_repudiation_B
atl_check ZG4 A_non_repudiation_B_reseau
atl_check ZG4 A_non_repudiation_B_Horloge
atl_check ZG4 A_non_repudiation_B_reseau_Horloge
atl_check ZG4 A_non_repudiation_reseau
atl_check ZG4 A_non_repudiation_reseau_Horloge
atl_check ZG4 A_non_repudiation_Horloge
atl_check ZG4 B_non_repudiation
atl_check ZG4 B_non_repudiation_A
atl_check ZG4 B_non_repudiation_A_reseau
atl_check ZG4 B_non_repudiation_A_Horloge
atl_check ZG4 B_non_repudiation_A_reseau_Horloge
atl_check ZG4 B_non_repudiation_reseau
atl_check ZG4 B_non_repudiation_reseau_Horloge
atl_check ZG4 B_non_repudiation_Horloge
exit

