read_module ZG3.rm
read_spec ZG3_ATL_B_non_repudiation.spec

atl_check ZG3 B_non_repudiation
atl_check ZG3 B_non_repudiation_A
atl_check ZG3 B_non_repudiation_A_reseau
atl_check ZG3 B_non_repudiation_A_Horloge
atl_check ZG3 B_non_repudiation_A_reseau_Horloge
atl_check ZG3 B_non_repudiation_reseau
atl_check ZG3 B_non_repudiation_reseau_Horloge
atl_check ZG3 B_non_repudiation_Horloge
exit
