read_module ZG3.rm
read_spec ZG3_ATL_Btimeliness.spec

atl_check ZG3 Btimeliness
atl_check ZG3 Btimeliness_A
atl_check ZG3 Btimeliness_A_B
atl_check ZG3 Btimeliness_A_Reseau
atl_check ZG3 Btimeliness_A_Horloge
atl_check ZG3 Btimeliness_A_B_Reseau
atl_check ZG3 Btimeliness_A_B_Horloge
atl_check ZG3 Btimeliness_A_Reseau_Horloge
atl_check ZG3 Btimeliness_A_B_Reseau_Horloge
atl_check ZG3 Btimeliness_B
atl_check ZG3 Btimeliness_B_Reseau
atl_check ZG3 Btimeliness_B_Horloge
atl_check ZG3 Btimeliness_B_Reseau_Horloge
atl_check ZG3 Btimeliness_Reseau
atl_check ZG3 Btimeliness_Reseau_Horloge
atl_check ZG3 Btimeliness_Horloge
exit