read_module ZG3.rm
read_spec ZG3_ATL_A_non_repudiation.spec

atl_check ZG3 A_non_repudiation
atl_check ZG3 A_non_repudiation_B
atl_check ZG3 A_non_repudiation_B_reseau
atl_check ZG3 A_non_repudiation_B_Horloge
atl_check ZG3 A_non_repudiation_B_reseau_Horloge
atl_check ZG3 A_non_repudiation_reseau
atl_check ZG3 A_non_repudiation_reseau_Horloge
atl_check ZG3 A_non_repudiation_Horloge
exit