read_module ZG3.rm
read_spec ZG3_ATL_Atimeliness.spec

atl_check ZG3 Atimeliness
atl_check ZG3 Atimeliness_A
atl_check ZG3 Atimeliness_A_B
atl_check ZG3 Atimeliness_A_Reseau
atl_check ZG3 Atimeliness_A_Horloge
atl_check ZG3 Atimeliness_A_B_Reseau
atl_check ZG3 Atimeliness_A_B_Horloge
atl_check ZG3 Atimeliness_A_Reseau_Horloge
atl_check ZG3 Atimeliness_A_B_Reseau_Horloge
atl_check ZG3 Atimeliness_B
atl_check ZG3 Atimeliness_B_Reseau
atl_check ZG3 Atimeliness_B_Horloge
atl_check ZG3 Atimeliness_B_Reseau_Horloge
atl_check ZG3 Atimeliness_Reseau
atl_check ZG3 Atimeliness_Reseau_Horloge
atl_check ZG3 Atimeliness_Horloge
exit